Ext.define('Awddy.enum.itemSlot', {
    singleton: true,

    Head: 'head',
    Neck: 'neck',
    Shoulder: 'shoulder',
    Back: 'back',
    Chest: 'chest',
    Wrist: 'wrist',
    Hands: 'hands',
    Waist: 'waist',
    Legs: 'legs',
    Feet: 'feet',
    Finger: 'finger',
    Finger1: 'finger1',
    Finger2: 'finger2',
    Trinket: 'trinket',
    Trinket1: 'trinket1',
    Trinket2: 'trinket2',
    MainHand: 'mainhand',
    OffHand: 'offhand',
    OneHand: 'onehand',
    TwoHand: 'twohand',
    Totem: 'totem',
});
