Ext.define('Awddy.enum.stat', {
    singleton: true,

    Strength: 'strength',
    Agility: 'agility',
    Stamina: 'stamina',
    Intellect: 'intellect',
    Spirit: 'spirit',

    Armor: 'armor',
    DefenseRating: 'defenserating',
    DodgeRating: 'dodgerating',
    ParryRating: 'parryrating',
    ShieldBlockValue: 'shieldblockvalue',
    ShieldBlockRating: 'shieldblockrating',
    FireResistance: 'fireresistance',
    FrostResistance: 'frostresistance',
    ShadowResistance: 'shadowresistance',
    ArcaneResistance: 'arcaneresistance',
    NatureResistance: 'natureresistance',
    ResilienceRating: 'resiliencerating',

    WeaponSpeed: 'weaponspeed',
    WeaponMinDamage: 'weaponmindamage',
    WeaponMaxDamage: 'weaponmaxdamage',
    AttackPower: 'attackpower',
    PhysicalCritRating: 'physicalcritrating',
    PhysicalHitRating: 'physicalhitrating',
    PhysicalHasteRating: 'physicalhasterating',
    ArmorPenetration: 'armorpenetration',
    ExpertiseRating: 'expertiserating',

    SpellPower: 'spellpower',
    SpellHealing: 'spellhealing',
    SpellCritRating: 'spellcritrating',
    SpellHitRating: 'spellhitrating',
    SpellHasteRating: 'spellhasterating',
    SpellPenetrationRating: 'spellpenetrationrating',
    ManaRegFive: 'manaregfive',
});
